name: venusta
services:
  db:
    image: pgvector/pgvector:pg17
    container_name: pg17-vector
    environment:
      POSTGRES_DB: venusta
      POSTGRES_USER: venusta
      POSTGRES_PASSWORD: venusta
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/001-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 30

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: venusta-api
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

  frontend:
    build:
      context: ./venusta-frontend
      dockerfile: Dockerfile
    container_name: venusta-frontend
    depends_on:
      api:
        condition: service_started
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  dbdata: